name: rris

dependencies:

  # basic
  - python=3.6
  - numpy
  - mkl
  - ipython
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - networkx
  - seaborn
  - pyyaml

  - pip:
    - opencv-python
    - open3d-python
    - pykinect2
    - pyrealsense2
